services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    google_recaptcha.validator.google_recaptcha_client:
        class: 'GuzzleHttp\Client'

    google_recaptcha.validator.google_recaptcha_validator:
        class: 'GoogleRecaptchaBundle\Validator\GoogleRecaptchaValidator'
        arguments:
            - '%google_recaptcha.api_endpoint%'
            - '%google_recaptcha.secret_key%'
            - '@request_stack'
            - '@google_recaptcha.validator.google_recaptcha_client'
            - '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'google_recaptcha' }
