services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GoogleRecaptchaBundle\Validator\GoogleRecaptchaValidatorClient:
        class: 'GuzzleHttp\Client'

    GoogleRecaptchaBundle\Validator\GoogleRecaptchaValidator:
        arguments:
            $apiEndpoint: '%google_recaptcha.api_endpoint%'
            $secretKey: '%google_recaptcha.secret_key%'
            $client: '@GoogleRecaptchaBundle\Validator\GoogleRecaptchaValidatorClient'
        tags:
            - { name: 'monolog.logger', channel: 'google_recaptcha' }
